# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
#      - image: circleci/mysql:5.7.18
#        environment:
#          MYSQL_DATABASE: "app"
#          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#          MYSQL_ROOT_HOST: "%"

    working_directory: /go/src/github.com/Chyroc/gor
    steps:
      - checkout
      - run: go get -u github.com/golang/lint/golint
      - run: if ["$(golint $(go list ./... | grep -v /vendor/))" == ""]; then exit 0; else exit 1; fi
      - run: go get -u github.com/rakyll/gotest
      - run: make checkstyle
      - run: make
      - run: make test